### ISSUE TITLE
Can't properly log messages until there's at least one console view attached.

### ISSUE THREAD

**Issue by autovalue** [jraska/Console#8]
I know that this was an explicit design choice. It would be useful for cases where the user is logging messages from a different screen/before the activity is launched. This way you don't miss important log information.

It would be nice if the user could choose to disable to `&& Console.consoleViewsCount() >= 1` check, or make the ConsoleTree a non-final class so that the user can override the `isLoggable()` method themselves.

**Comment by jraska** [comment]
Hello, thank you for reporting this.
To be honest I cannot remember why I added this check, because Console is now designed to store and display messages reported before any Console view is attached so it will be handled properly.

I will remove the check, because it is not necessary and I will release it today. As it is minor change in behaviour, it will be version 0.4.2.

**Comment by jraska** [comment]
About the non-final ConsoleTree, I don't want to open it for inheritance, since there shouldn't be anything else then just colouring of output based on log level - another argument why this console view count should not be there :)

**Comment by jraska** [comment]
Released in version 0.4.2

**Comment by autovalue** [comment]
Thanks for being so quick to resolve the issue!
